# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'
env:
  FRONTEND_COMMIT_HASH:
    sh: ./scripts/get-commit-hash.sh .git/modules/frontend
  CMS_COMMIT_HASH:
    sh: ./scripts/get-commit-hash.sh .git/modules/cms


tasks:
  web-build-frontend:
    cmds:
      - docker compose --profile web-builds up --build --abort-on-container-exit frontend
  web-build-cms:
    cmds:
      - docker compose --profile web-builds up --build --abort-on-container-exit cms
  web-builds:
    cmds:
      - task: web-build-frontend
      - task: web-build-cms
      - echo "Success"
